title: Change goal material when the ball reaches it
hero_image: images/banner.png
description: Change goal material when the ball reaches it
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Change goal material when the ball reaches it
